import pandas as pd
import os
import numpy as np
import geopandas as gp
from sqlalchemy import create_engine

# # local module import
# from credentials import sql_engine_string_generator

# # create the sql engine from a string generated by the string generator
# sql_engine_string=sql_engine_string_generator('QP_SERVER','QP_HGEE_USER','QP_HGEE_PASSWORD','hgee')
# sql_engine=create_engine(sql_engine_string)

# sql_query = """
#                 set time zone GMT;
#                 select distinct on (site) site, latdecd, londecd from all__hgee_v2 order by site limit 100;
#             """
# with sql_engine.connect() as conn:
# # create the dataframes from the sql query
#     site_coords_df=pd.read_sql_query(sql_query, conn)

# project	IPCC_region	UNEP_region	country	station	lat	lon	matrix	method	species	start_time	end_time	quantity	units	flag
# for now an alternate source (shared csv file)
df = pd.read_csv(r'C:/Users/firanskib/OneDrive - EC-EC/mercury/ECCC_Global_Passives_2024-10-17.csv')
# Subset the dataframe to include only selected sitecodes
df_subset = df[df['sitecode'].isin(['AP1', 'HG24', 'HG28'])]

# Update the coordinates for sitecode 'AP1' using .loc
df_subset.loc[df_subset['sitecode'] == 'AP1', ['latdecd', 'londecd']] = [-6.2088, 108.8455] 
df_subset.loc[df_subset['sitecode'] == 'HG24', ['latdecd', 'londecd']] = [21.05, 105.88] 
df_subset.loc[df_subset['sitecode'] == 'HG28', ['latdecd', 'londecd']] = [6.984302, -2.39068]    

# set only the unique values
site_coords_unique_df = df_subset.drop_duplicates()

# create a geodf from coords_df
#site_coords_gdf = gp.GeoDataFrame(site_coords_df, geometry=gp.points_from_xy(site_coords_df.londecd, site_coords_df.latdecd), crs="EPSG:4326")
site_coords_gdf = gp.GeoDataFrame(site_coords_unique_df, geometry=gp.points_from_xy(site_coords_unique_df.londecd, site_coords_unique_df.latdecd), crs="EPSG:4326")
print (site_coords_gdf)

# import the ipcc shape file
shapefile_path = "C:/Users/firanskib/OneDrive - EC-EC/mercury/IPCC_shapefiles/IPCC-WGI-reference-regions-v4.shp"
ipcc_regions = gp.read_file(shapefile_path)

ipcc_polygons = ipcc_regions.geometry

for i,point in enumerate(site_coords_gdf.geometry):
    site_boolean = ipcc_polygons.geometry.contains(point)
    site=site_coords_gdf.loc[site_coords_gdf.index[i],'site']
    ipcc_region=ipcc_regions.loc[site_boolean[site_boolean].index,'Name']
    ipcc_region = ipcc_region.loc[ipcc_region.index[0]]
    site_coords_unique_df.loc[site_coords_unique_df['site']==site,'IPCC_region']=ipcc_region

print (site_coords_unique_df)

# site_coords_unique_df.to_csv('\\\econm3hwvfsp008.ncr.int.ec.gc.ca/arqp_data/Projects/OnGoing/Mercury/HGEE-Minamata/Data/Passives/data_files/global_passives_geolocation.csv',index=False)