# this program does OESG analysis:
# average and std dev for sites
# box plots of sites for ipcc_regions
# Mann Kendall trends
# pick what this program does by turning various functions on and off


import numpy as np
from datetime import datetime as dt
from datetime import timedelta
import calendar
from calendar import monthrange
import glob
import pandas as pd
from pandas.tseries.offsets import MonthEnd
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.ion()
import pymannkendall as mk
from pymannkendall import original_test  # original MK
from sqlalchemy import create_engine, text, update, Table, MetaData, func, insert
from sqlalchemy.exc import SQLAlchemyError
import geopandas as gp
import matplotlib.dates as md
from shapely import Point
from shapely.geometry import box 
import matplotlib as mpl
from scipy import stats
from scipy.stats import linregress
import os
import re
import shutil
from collections import defaultdict
from libpysal.weights import KNN
from esda.moran import Moran
import logging
from dotenv import load_dotenv

# local module import
from credentials import sql_engine_string_generator

# set logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create a console handler for logging debug output
console_handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s | %(name)s | %(levelname)s | %(message)s')
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)

################## SQL database stuff ##############################

# create the sql engine from a string generated by the string generator
sql_engine_string = sql_engine_string_generator('QP_SERVER','QP_HGEE_USER','QP_HGEE_PASSWORD','hgee')
sql_engine = create_engine(sql_engine_string)

################### common data IO elements ##########################

# import the ipcc_regions as a dataframe
sql_data_query = """
                select distinct on (ipcc_region) ipcc_region from sites order by ipcc_region;
                """
with sql_engine.connect() as conn:
    ipcc_analysis_df = pd.read_sql_query(sql_data_query, conn)


# initialize the dataframe for ipcc mann_kendall results
ipcc_analysis_df.set_index('ipcc_region', drop=True, inplace=True) # set the ipcc_regions as the index
ipcc_analysis_df['mk_slope']=np.nan # add a blank list for the MK results

ipcc_regions_list = ipcc_analysis_df.index.to_list()
ipcc_regions_list = ['N.W.North-America']#,'N.E.North-America','W.North-America'] # a temporary list for testing

# initialize a dataframe for monthly averages 
ipcc_master_df=pd.DataFrame() # create an empty dataframe to house each concentration query by ipcc_region column

# grab the sites list from the sites table
sql_data_query = """
                SELECT CONCAT( sites.site, ' (', sites.country_code, ')') AS site_name_full
                from sites
                where ipcc_region = '{}'
                order by site_name_full
                """
with sql_engine.connect() as conn:
    sites_df = pd.read_sql_query(sql_data_query, conn)



def minamata_wet_dep_stats():
    mercury_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_deposition.csv') # don't index the first column yet

    # set up a blank dataframe to house all the stats data
    year_list = list(range(2010, 2025))
    stats_columns = [f"{year}_{stat}" for year in year_list for stat in ['wght_mn', 'std_dev', 'min', '5_p', '25_p', 'med', '75_p', '95_p', 'max']]
    deposition_stats_df = pd.DataFrame(columns=stats_columns, index=mercury_df['site'].unique())

    # clean up data
    mercury_df.loc[mercury_df['concentration']==-999.0,'flag_orig'] = 'C'
    mercury_df.loc[mercury_df['deposition']==-999.0,'flag_orig'] = 'C'
    mercury_df.loc[mercury_df['mm']==-999.0,'flag_orig'] = 'C'
    # filter out the missing entries to NaNs

    # Filter out flagged values
    mercury_df['flag_orig'] = mercury_df['flag_orig'].astype(str).str.strip()
    flags_to_exclude = ['C','890','780','783','999','899']
    mercury_df.loc[mercury_df['flag_orig'].isin(flags_to_exclude), ['mm','concentration','deposition']] = pd.NA

    # print(mercury_df.loc[mercury_df['mm'] < 0, ['datetime', 'mm']])
    # print(mercury_df.loc[mercury_df['concentration'] < 0, ['datetime', 'deposition']])
    
    # set a blank list of stats dataframes
    all_site_stats = []

    # set up a list of residual series for each site
    residuals = []

    # do analysis for each site sub_df
    for site, site_df in mercury_df.groupby('site'):
        # print(site)

        site_df = site_df.copy()
        site_df.set_index('datetime', drop=True, inplace=True)
        site_df.index = pd.to_datetime(site_df.index, errors='coerce')
        site_df['month'] = site_df.index.month
        site_df['year'] = site_df.index.year
        # skip sites with too short a data length
        if site_df.index.max() < pd.Timestamp('2016-01-01'):
            continue

        # # Pre-calculate log values
        # site_df = site_df[(site_df['concentration'] > 0) & (site_df['mm'] > 0)]
        # site_df['log_mm'] = np.log(site_df['mm'])
        # site_df['log_Hg'] = np.log(site_df['concentration'])


        # def safe_linreg(g):
        #     try:
        #         slope, intercept, *_ = linregress(g['log_mm'], g['log_Hg'])
        #         return pd.Series({'slope': slope, 'intercept': intercept})
        #     except ValueError as e:
        #         print(f"Regression failed for site: {site}, month: {g.name}, reason: {e}")
        #         return pd.Series({'slope': np.nan, 'intercept': np.nan})
        #         # Step 1: Compute slope and intercept per month (across all years)
        # monthly_models = (
        #     site_df.groupby('month')
        #     .apply(safe_linreg, include_groups=False)
        # )

        # monthly_models.index.name = 'month'
        # monthly_models = monthly_models.reset_index()

        # # store the original index
        # original_index = site_df.index

        # # Step 2: Map slope/intercept to each row based on month
        # site_df = site_df.merge(monthly_models, on='month', how='left')

        # # Restore datetime index
        # site_df.index = original_index

        # # Step 3: Compute predicted log(Hg), residuals, and weighted residuals
        # site_df['log_Hg_pred'] = site_df['slope'] * site_df['log_mm'] + site_df['intercept']
        # site_df['residual'] = site_df['log_Hg'] - site_df['log_Hg_pred']
        # site_df['weighted_residual'] = site_df['residual'] * site_df['mm']

        # # Map month numbers to 3-letter names
        # month_map = {
        #     1: 'residual_jan', 2: 'residual_feb', 3: 'residual_mar', 4: 'residual_apr',
        #     5: 'residual_may', 6: 'residual_jun', 7: 'residual_jul', 8: 'residual_aug',
        #     9: 'residual_sep', 10: 'residual_oct', 11: 'residual_nov', 12: 'residual_dec'
        # }

        # # Create a new column name for each row based on its month
        # site_df['residual_col'] = site_df['month'].map(month_map)

        # # Create wide-format DataFrame where each row has weighted_residual in the correct month column
        # residual_wide = pd.pivot_table(
        #     site_df[['weighted_residual', 'residual_col']],
        #     index=site_df.index,
        #     columns='residual_col',
        #     values='weighted_residual'
        # )

        # # do a monthly average for each site for each year
        # # Group by year and month, then take the average of weighted_residual
        # monthly_avg = (
        #     site_df
        #     .groupby(['year', 'month'])['weighted_residual']
        #     .mean()
        #     .reset_index()
        # )

        # # Map numeric month to named columns
        # monthly_avg['month_name'] = monthly_avg['month'].map(month_map)

        # # Pivot to wide format: year as index, month columns as values
        # monthly_avg_pivot = (
        #     monthly_avg
        #     .pivot(index='year', columns='month_name', values='weighted_residual')
        #     .sort_index()
        # )

        # # (Optional) ensure all 12 columns are present in case some months are missing
        # for col in month_map.values():
        #     if col not in monthly_avg_pivot.columns:
        #         monthly_avg_pivot[col] = np.nan

        # # Reorder columns to ensure Jan–Dec order
        # monthly_avg_pivot = monthly_avg_pivot[month_map.values()]
        # monthly_avg_pivot = monthly_avg_pivot.reset_index()
        # monthly_avg_pivot['year'] = monthly_avg_pivot['year'].astype(str)  # index now object/string
        # monthly_avg_pivot.set_index('year', inplace=True)        

        # mk_results = {} # set up a mk results dictionary

        # for col in monthly_avg_pivot.columns:
        #     series = monthly_avg_pivot[col].dropna()
        #     if len(series) >= 3:
        #         result = mk.original_test(series)
        #         mk_results[col] = {
        #             'slope': result.slope,
        #             'p': result.p,
        #             'trend': result.trend
        #         }
        #     else:
        #         mk_results[col] = {
        #             'slope': np.nan,
        #             'p': np.nan,
        #             'trend': 'insufficient'
        #         }

        # # Turn into DataFrame: rows = slope, p, trend
        # mk_df = pd.DataFrame(mk_results) 

        # # Reindex MK result so it becomes part of the same structure
        # mk_df.index.name = 'year'  # mimic index name
        # monthly_avg_pivot = pd.concat([monthly_avg_pivot, mk_df])

        # # Join these new columns back to the original site_df
        # site_df = pd.concat([site_df, residual_wide], axis=1)

        # # save each site_df to file for examination
        # site_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_deposition_table_'+site+'.csv')
        # monthly_avg_pivot.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_deposition_MK_results_'+site+'.csv')
    
        def annual_stats_func(g):
            mm_sum = g['mm'].sum()
            weighted_avg = (g['concentration'] * g['mm']).sum() / mm_sum if mm_sum != 0 and not pd.isna(mm_sum) else np.nan
            return pd.Series({
                'wght_mn': weighted_avg,
                'std_dev': g['concentration'].std(),
                'min': g['concentration'].min(),
                '05_p': g['concentration'].quantile(0.05),
                '25_p': g['concentration'].quantile(0.25),
                'med': g['concentration'].median(),
                '75_p': g['concentration'].quantile(0.75),
                '95_p': g['concentration'].quantile(0.95),
                'max': g['concentration'].max()
            })

        
        
        def annual_plot_func(df, site):
            if df['concentration'].dropna().empty or df['year'].nunique() < 2:
                print(f"Skipping plot for {site}: not enough valid Hg data.")
                return

            fig, ax = plt.subplots(figsize=(10, 8))
            df.boxplot(column='concentration', by='year', ax=ax)
            plt.xticks(rotation=45)  # Rotate x-axis tick labels
            plt.title(f'Annual Wet Deposition Boxplot for {site}')
            plt.suptitle("")  # Remove the automatic 'Boxplot grouped by year' title
            plt.xlabel('Year')
            plt.ylabel('Hg Concentration (ng/L)')
            plt.tight_layout()
            out_path = rf'C:/Users/firanskib/OneDrive - EC-EC/mercury/Minamata_wet_deposition/annual_wet_dep_boxplot_{site}.png'
            plt.savefig(out_path)
            plt.close()

        try:

            # # Apply by year and month to assign monthly precip-weighted residual to each row
            # monthly_df = site_df.groupby(['year', 'month'], group_keys=False).apply(monthly_weighted_residuals)
            # site_df['year'] = site_df.index.year

            # Annual stats
            annual_stats = site_df.groupby('year').apply(annual_stats_func, include_groups=False)
            deposition_stats_series = annual_stats.T.stack().reorder_levels([1, 0]).sort_index()
            deposition_stats_series.index = [f"{year}_{stat}" for year, stat in deposition_stats_series.index]
            deposition_stats_df = deposition_stats_series.to_frame().T
            deposition_stats_df.index = [site]
            all_site_stats.append(deposition_stats_df)

            # Plot
            # annual_plot_func(site_df, site)

            # # set up a table of residuals for all the sites with datetime as the index
            # resid_df = site_df['weighted_residual'].rename(site) # set up a temp dataframe
            # residuals.append(resid_df) # append the dataframes horizontally




        except Exception as e:
            print(f"Failed for site {site}: {e}")

    # Concatenate all sites into a full DataFrame
    final_deposition_stats_df = pd.concat(all_site_stats)
    # print (final_deposition_stats_df.columns)
    # save to file
    final_deposition_stats_df.to_csv(r'C:/Users/firanskib/OneDrive - EC-EC/mercury/Minamata_wet_deposition/minamata_wet_deposition_stats.csv')



def minamata_wet_dep_m_k_analysis():
    # --- Load data ---
    mercury_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_deposition.csv') # don't index the first column yet

    # Mark invalid values with flag 'C'
    for col in ['concentration','deposition','mm']:
        mercury_df.loc[mercury_df[col]==-999, 'flag_orig'] = 'C'

    # Filter out flagged values
    mercury_df['flag_orig'] = mercury_df['flag_orig'].astype(str).str.strip()
    flags_to_exclude = ['C','890','780','783','999','899']
    mercury_df.loc[mercury_df['flag_orig'].isin(flags_to_exclude), ['mm','concentration','deposition']] = pd.NA

    # Drop rows missing any key variable
    # mercury_df = mercury_df.dropna(subset=['mm','concentration','deposition'])

    # # Ensure consistent datetime format
    # for col in ['start_dt','end_dt','datetime']:
    #     mercury_df[col] = pd.to_datetime(mercury_df[col], errors='coerce')

    # print (mercury_df['start_dt'])
    
    # --- 2. Monthly aggregation function (prorated) ---
    def monthly_aggregates(df, start_col="start_dt", end_col="end_dt", agg_map=None):
        from calendar import monthrange
        import numpy as np
        
        df = df.copy()
        df[start_col] = pd.to_datetime(df[start_col])
        df[end_col] = pd.to_datetime(df[end_col])
        records = []

        for _, row in df.iterrows():
            start = row[start_col]
            end = row[end_col]

            # if row['country'] in ["Canada", "United States"]:
            #     print(f"[DEBUG] Site={row['site']}, Country={row['country']}, Start={start}, End={end}")

            if pd.isna(start) or pd.isna(end) or end <= start:
                continue

            total_days = (end - start).days
            if total_days <= 0:
                continue

            current = start
            while current < end:
                y, m = current.year, current.month
                last_day = pd.Timestamp(year=y, month=m, day=monthrange(y, m)[1])
                seg_end = min(end, last_day + pd.Timedelta(days=1))
                seg_days = (seg_end - current).days

                if end <= start:
                    print(f"Bad interval at {row['site']} ({row['country']}): start={start}, end={end}")
                    continue

                if seg_days > 0:
                    rec = {"year": y, "month": m, "days": seg_days}
                    for col, how in agg_map.items():
                        val = row[col]
                        if pd.isna(val):
                            continue
                        if how == "sum":
                            rec[col] = (val / total_days) * seg_days
                        elif how == "prorated_mean":
                            rec[col] = (val / total_days) * seg_days
                            rec[f"{col}_weight"] = seg_days
                        elif how == "pwc":
                            if pd.isna(row["mm"]):
                                continue
                            prorated_mm = (row["mm"] / total_days) * seg_days
                            rec[f"{col}_num"] = val * prorated_mm
                            rec[f"{col}_den"] = prorated_mm
                    records.append(rec)
                current = seg_end

        prorated = pd.DataFrame(records)
        if prorated.empty:
            return pd.DataFrame(columns=["year","month"] + list(agg_map.keys()))

        def agg_func(g):
            out = {}
            for col, how in agg_map.items():
                if how == "sum":
                    out[col] = g[col].sum()
                elif how == "prorated_mean":
                    if f"{col}_weight" in g:
                        out[col] = np.average(g[col], weights=g[f"{col}_weight"])
                    else:
                        out[col] = g[col].mean()
                elif how == "pwc":
                    num = g[f"{col}_num"].sum()
                    den = g[f"{col}_den"].sum()
                    out[col] = num / den if den > 0 else pd.NA
            return pd.Series(out)

        out = prorated.groupby(["year","month"]).apply(agg_func, include_groups=False).reset_index()
        out["datetime"] = pd.to_datetime(out["year"].astype(str) + "-" + out["month"].astype(str) + "-15")
        return out

    # --- 3. Aggregation map ---
    agg_map = {
        "mm": "sum",
        "deposition": "prorated_mean",
        "concentration": "pwc"
    }

    # --- 4. Loop through sites to build full monthly_df ---
    monthly_dfs = []

    # define a cut-off date to split the trend analysis before and after Minamata
    cutoff = pd.Timestamp("2013-01-01")

    for site_name, site_df in mercury_df.groupby('site'):
        # print (site_df.index)
        site_df['start_dt'] = pd.to_datetime(site_df['start_dt'], errors='coerce')
        site_df['end_dt'] = pd.to_datetime(site_df['end_dt'], errors='coerce')
        site_df['datetime'] = pd.to_datetime(site_df['datetime'], errors='coerce')

        # find min and max datetimes
        dt_min = site_df['start_dt'].min()
        dt_max = site_df['end_dt'].max()

        # check timespan coverage
        span_years = (site_df['start_dt'].max() - site_df['start_dt'].min()).days / 365.25

        # filter: must start before 2010 and end after 2016
        if dt_min >= pd.Timestamp("2010-01-01") or dt_max <= pd.Timestamp("2016-12-31"):
            print(f"⚠️ Skipping {site_name} — span not wide enough ({dt_min.date()} to {dt_max.date()})")
            continue

            # remove sites with fewer than 5 years of data
        if span_years < 5:
            print(f"⚠️ Skipping {site_name} — only {span_years:.1f} years of data")
            continue

        country_name = site_df['country'].iloc[0] if 'country' in site_df else "<unknown>"
        # print (f"Processing site: {site_name} ({country_name})")
        site_monthly = monthly_aggregates(site_df, agg_map=agg_map)
        if site_monthly.empty:
            print(f"⚠️ Warning: site '{site_name}' ({country_name}) produced an empty monthly DataFrame")
            continue
        site_monthly['site'] = site_name
        site_monthly['country'] = country_name
        monthly_dfs.append(site_monthly)

    monthly_df = pd.concat(monthly_dfs, ignore_index=True)

    # --- 5. Seasonal Mann-Kendall trend ---
    def compute_smk_annual_trends(
        monthly_df,
        variables=['concentration','deposition','mm'],
        alpha=0.05,
        mode="pre",
        significance_thresholds=None
    ):
        """
        Compute seasonal Mann–Kendall trends and annual slope for multiple variables, by site,
        and add alternate significance criteria.

        Returns a DataFrame including both significance tests.
        """
        results = []
        if significance_thresholds is None:
            significance_thresholds = {}

        for site, site_df in monthly_df.groupby('site'):
            site_df = site_df.copy()
            # Apply cutoff using datetime column
            if mode == "pre":
                site_df = site_df[site_df["datetime"] < cutoff]
            elif mode == "post":
                site_df = site_df[site_df["datetime"] >= cutoff]

            site_df['season'] = site_df['month']

            if len(site_df) < 12:
                continue

            for var in variables:
                var_series = site_df[var].dropna()
                if len(var_series) < 12:
                    continue

                try:
                    res = mk.seasonal_test(var_series.values, period=12)
                except Exception as e:
                    print(f"❌ Error processing {site} {var}: {e}")
                    continue

                annual_slope = res.slope * 12

                # Null-hypothesis significance test
                p_significant = res.p < alpha

                # Alternate numeric threshold significance test
                threshold_value = significance_thresholds.get(var)
                alt_significant = None
                if threshold_value is not None:
                    alt_significant = abs(annual_slope) >= threshold_value
                else:
                    alt_significant = p_significant  # fallback

                results.append({
                    "site": site_name,
                    "mode": mode,
                    "trend": res.trend,
                    "p_value": res.p,
                    "significant": res.p < 0.05,
                    "seasonal_slope_per_month": res.slope,
                    "annual_slope": res.slope * 12,
                    "n": len(site_df),
                    "years_span": span_years,
                    "start": site_df["datetime"].min(),
                    "end": site_df["datetime"].max()
                })
        return pd.DataFrame(results)
    
    # --- 6. Run the SMK analysis ---
    # set thresholds as the median of the annual slopes from the original MK analysis
    thresholds = {
        'mm': 8,            # mm/year slope threshold
        'deposition': 13,    # deposition/year slope threshold
        'concentration': 0.6 # concentration/year slope threshold
    }

    pre_smk_df = compute_smk_annual_trends(monthly_df, mode="pre", significance_thresholds=thresholds)
    post_smk_df = compute_smk_annual_trends(monthly_df, mode="post", significance_thresholds=thresholds)

    # Merge side-by-side
    comparison_df = pd.merge(
        pre_smk_df,
        post_smk_df,
        on="site",
        suffixes=("_pre2013", "_post2013")
    )

    print(comparison_df.head())
    comparison_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\comparison_df.csv', index=False)


def m_k_summary():
    path = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\M-K_wet_deposition_files\*MK*.csv'
    path_list=glob.glob(path)
    for path in path_list:
        filename = os.path.basename(path)
        prefix = "hgee_wet_deposition_MK_results_"
        suffix = ".csv"
        if filename.startswith(prefix) and filename.endswith(suffix):
            site_name = filename[len(prefix):-len(suffix)]

        # out path for fig saving
        out_path = rf'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\M-K_wet_deposition_files\wet_dep_monthly_M-K_plot_{site_name}.png'


        # load the dataframe
        df = pd.read_csv(path, index_col=0)
        if (df.loc['trend',:] == 'insufficient').sum() > 6:
            print ('skipping ',site_name)
            continue
        else:
            print ('plotting ',site_name)
            slope_series = pd.to_numeric(df.loc['slope'], errors='coerce')
            p_series = pd.to_numeric(df.loc['slope'], errors='coerce')
            # Plotting
            fig, ax = plt.subplots(figsize=(12, 6))

            # X-axis labels: remove "residual_" prefix for clarity
            months = [col.replace('residual_', '') for col in slope_series.index]

            ax.bar(months, slope_series.values, color='skyblue', edgecolor='black')

            # Annotate with p-values
            for i, (month, val) in enumerate(slope_series.items()):
                p_val = p_series[month]
                    # Handle string values or non-numeric p-values
                try:
                    p_numeric = float(p_val)
                    label = f"P: {p_numeric:.2f}"
                except (ValueError, TypeError):
                    label = "P: n/a"

                # Position text above for positive bars, below for negative bars
                offset = 8 if val >= 0 else -14
                valign = 'bottom' if val >= 0 else 'top'

                # annotate the bars with the P-value
                ax.annotate(label, xy=(i, val), xytext=(0, offset),
                            textcoords="offset points", ha='center', va=valign,
                            fontsize=9, color='darkgreen')
            
            # Horizontal zero line
            ax.axhline(0, color='gray', linestyle='--', linewidth=1)

            # Formatting
            ax.set_title(site_name+" Monthly M-K Mercury Trends with P-values", fontsize=14)
            ax.set_xlabel("Month")
            ax.set_ylabel("M-K Senn Slope (yr$^{-1}$)")
            ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.savefig(out_path)
            plt.close(fig)


def m_k_clustering():
    mk_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_seasonal_M-K_results.csv')
    # ipcc_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_dep_sites_by_ipcc.csv')

    # # --- Merge on site/site name ---
    # mk_df = mk_df.merge(ipcc_df, on='site', how='inner')

    # # Loop through quarters and compute correlations
    # for q in range(1, 5):
    #     dep_col = f"dep_trend_Q{q}"
    #     pwc_col = f"pwc_trend_Q{q}"
    #     corr_col = f"dep-pwc_correlation_Q{q}"

    #     def compare_trends(row):
    #         dep = str(row[dep_col]).strip().lower()
    #         pwc = str(row[pwc_col]).strip().lower()

    #         if dep == "no trend" or pwc == "no trend":
    #             return "no correlation"
    #         elif dep == pwc:
    #             return "positive correlation"
    #         else:
    #             return "negative correlation"

    #     mk_df[corr_col] = mk_df.apply(compare_trends, axis=1)

    # # Sort by ipcc_region
    # mk_df = mk_df.sort_values("ipcc_region")
    # mk_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_seasonal_M-K_results.csv', index=False)

    # # Save or inspect
    # print(mk_df.head())

    # --- Choose the trend column you want to test ---
    # Example: test clustering for Q1 precip-weighted concentration slope
    slope_cols = [c for c in mk_df.columns if "slope" in c]
    slope_identifiers = [c.replace("slope_", "") for c in slope_cols]

    # split the dataframe into America and Europe
    mk_df_america = mk_df[mk_df['ipcc_region'].str.contains("America", na=False)]
    mk_df_europe = mk_df[mk_df['ipcc_region'].str.contains("Europe", na=False)]

    def mi_calculator(slope_series, lat_series, lon_series):

        # logger.debug(f"{'slope_series'}: {slope_series}")
        # logger.debug(f"{'lat_series'}: {lat_series}")
        # logger.debug(f"{'lon_series'}: {lon_series}")
        
        mk_df['trend_val'] = slope_series

        # --- Convert to GeoDataFrame ---
        gdf = gp.GeoDataFrame({"trend_val": slope_series}, geometry=gp.points_from_xy(lon_series, lat_series), crs="EPSG:4326")

        # --- Build spatial weights: k nearest neighbors ---
        w = KNN.from_dataframe(gdf, k=3)
        w.transform = 'R'  # row-standardize weights

        # --- Run Moran's I ---
        mi = Moran(gdf['trend_val'], w, permutations=999)
        return mi.I, mi.p_sim

    records_am = []
    records_eu = []


    for i, col in enumerate(slope_cols):
        identifier = slope_identifiers[i]
        I_val_am, p_val_am = mi_calculator(mk_df_america[col],mk_df_america['latdecd'],mk_df_america['londecd'] )
        I_val_eu, p_val_eu = mi_calculator(mk_df_europe[col],mk_df_europe['latdecd'],mk_df_europe['londecd'])
        records_am.append({
            "identifier": identifier,
            "I_america": I_val_am,
            "p_america": p_val_am
        })
        records_eu.append({
            "identifier": identifier,
            "I_europe": I_val_eu,
            "p_europe": p_val_eu
        })

    mi_results_am_df = pd.DataFrame(records_am)
    mi_results_eu_df = pd.DataFrame(records_eu)

    wet_dep_moranI_df = mi_results_am_df.merge(mi_results_eu_df, on='identifier')

    wet_dep_moranI_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_moranI_results.csv', index=False)
    logger.debug("\nwet_dep_moranI_df:\n%s", wet_dep_moranI_df)


def wet_dep_insert(sql_engine):
    wet_dep_sites_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Data\US\mdn.csv')

    # insert missing latdecd and londecd into the hgee_active table
    with sql_engine.connect() as conn:
        metadata = MetaData()
        hgee_active = Table('hgee_active', metadata, autoload_with=sql_engine)

        for idx, row in wet_dep_sites_df.iterrows():
            site = row['site']
            latdecd = row['latdecd']
            londecd = row['londecd']

            stmt = (
                update(hgee_active)
                .where(hgee_active.c.site == site)
                .values(latdecd=latdecd, londecd=londecd)
            )

            try:
                result = conn.execute(stmt)
                if result.rowcount > 0:
                    print(f"Updated site {site} with lat: {latdecd}, lon: {londecd}")
                else:
                    print(f"No matching site found for {site}.")
            except SQLAlchemyError as e:
                print(f"Error updating site {site}: {e}")

def wet_dep_sites(sql_engine):
    # grab the sites list from the sites table
    sql_data_query = """
                    SELECT distinct on (site) site, latdecd, londecd from hgee_active order by site;
                    """
    with sql_engine.connect() as conn:
        sites_df = pd.read_sql_query(sql_data_query, conn)
    
    # sites_df.set_index('site', drop=True, inplace=True) # set the sites as the index
    wet_dep_m_k_results_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_wet_deposition_annual_mk_summary.csv')

    # Clean up site column: remove all spaces
    sites_df['site'] = sites_df['site'].str.replace(" ", "", regex=False)
    wet_dep_m_k_results_df['site'] = wet_dep_m_k_results_df['site'].str.replace(" ", "", regex=False)

    merged_df = wet_dep_m_k_results_df.merge(sites_df, on='site', how='left')
    merged_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_annual_M-K_results_2025-10-02.csv', index=False)
    print (merged_df.head())

# wet dep stats function
# minamata_wet_dep_stats()

# wet dep seasonal m-k function
# minamata_wet_dep_m_k_analysis()

# follow up on mk analysis for summary
# m_k_summary()

# spatial clustering of m-k trends
# m_k_clustering()

# wet dep sites with lat/lon
wet_dep_sites(sql_engine)

# wet dep insert function
# wet_dep_insert(sql_engine)

