import os
import pymannkendall as mk
import numpy as np
import pandas as pd
from scipy.stats import chi2
import calendar
from sqlalchemy import create_engine, text, update, Table, MetaData, func, insert
from sqlalchemy.exc import SQLAlchemyError
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import datetime as dt
import glob
import re
from io import StringIO
from pathlib import Path
import logging

# local module import
from credentials import sql_engine_string_generator

# set logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Create a console handler for logging debug output
console_handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s | %(name)s | %(levelname)s | %(message)s')
console_handler.setFormatter(formatter)
logger.addHandler(console_handler)

################## SQL database stuff ##############################

# create the sql engine from a string generated by the string generator
sql_engine_string = sql_engine_string_generator('QP_SERVER','QP_HGEE_USER','QP_HGEE_PASSWORD','hgee')
sql_engine = create_engine(sql_engine_string)


def monthly_averaging():
    def monthly_precip_stats(df, start_col, end_col, mm_col, conc_col, dep_col, flag_col, site_col=None):
        """
        Calculate monthly precipitation stats for each site:
        - Weighted mean precipitation (mm_mean)
        - Precipitation-weighted mean concentration (pwc)
        - Weighted mean deposition (dep_mean)
        Handles intervals that straddle month boundaries.

        Parameters:
            df: pd.DataFrame
            start_col, end_col: str - datetime columns
            mm_col: str - precipitation column
            conc_col: str - concentration column
            dep_col: str - deposition column
            flag_col: str - flag column for filtering
            site_col: str or None - site column if multiple sites

        Returns:
            pd.DataFrame: site (if given), month, mm_mean, pwc, dep_mean
        """

        all_rows = []

        # Filtering step

        # read in the csv file for flag mapping
        flag_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\flag_mapping.csv')

       # Select Project_flag values where DES_flag is in ['M1', 'M2']
        flags_to_exclude = flag_df.loc[flag_df['DES_flag'].isin(['M1', 'M2']), 'Project_flag'] \
            .astype(str) \
            .str.strip() \
            .tolist()

        print(flags_to_exclude)
        df[flag_col] = df[flag_col].astype(str).str.strip()

        # remove the flagged values
        df.loc[df[flag_col].isin(flags_to_exclude), [mm_col, conc_col, dep_col]] = pd.NA

        # remove negative values
        df[[mm_col, conc_col, dep_col]] = df[[mm_col, conc_col, dep_col]].mask(df[[mm_col, conc_col, dep_col]] < 0, pd.NA)



        for _, row in df.iterrows():
            start = pd.to_datetime(row[start_col])
            end = pd.to_datetime(row[end_col])
            mm = row[mm_col]
            conc = row[conc_col]
            dep = row[dep_col]

            if pd.isna(mm) or mm <0:
                continue
            elif pd.isna(conc) or conc <0:
                continue
            elif  pd.isna(dep) or dep <0:
                continue

            months = pd.date_range(start=start.normalize(), end=end.normalize(), freq='MS')
            if len(months) == 0:
                months = [start.normalize()]

            split_points = [start] + list(months[1:]) + [end]

            for i in range(len(split_points) - 1):
                seg_start = split_points[i]
                seg_end = split_points[i + 1]
                if seg_end > end:
                    seg_end = end

                duration = (seg_end - seg_start).total_seconds()
                total_duration = (end - start).total_seconds()
                if total_duration == 0:
                    weight = 1.0
                else:
                    weight = duration / total_duration

                month = seg_start.to_period('M').start_time

                row_data = {
                    'month': month,
                    'mm_segment': mm * weight,
                    'conc_segment': conc if pd.notna(conc) else np.nan,
                    'dep_segment': dep if pd.notna(dep) else np.nan,
                    'duration': duration,
                    'weight': weight
                }
                if site_col:
                    row_data['site'] = row[site_col]

                all_rows.append(row_data)

        seg_df = pd.DataFrame(all_rows)

        group_cols = ['month']
        if site_col:
            group_cols = ['site'] + group_cols

        monthly = seg_df.groupby(group_cols).agg(
            mm_sum=('mm_segment', 'sum'),
            mm_duration_sum=('duration', 'sum'),
            conc_mm_sum=('mm_segment', lambda x: np.nansum(x * seg_df.loc[x.index, 'conc_segment'])),
            mm_sum_for_conc=('mm_segment', lambda x: np.nansum(x[seg_df.loc[x.index, 'conc_segment'].notna()])),
            dep_sum=('dep_segment', lambda x: np.nansum(x * seg_df.loc[x.index, 'weight'])),
            weight_sum=('weight', 'sum')
        ).reset_index()

        # Final calculations
        monthly['mm_mean'] = monthly['mm_sum'] / monthly['weight_sum']        # Weighted mean precipitation
        monthly['pwc'] = monthly['conc_mm_sum'] / monthly['mm_sum_for_conc']  # Precipitation-weighted concentration
        monthly['dep_mean'] = monthly['dep_sum'] / monthly['weight_sum']     # Weighted mean deposition

        return monthly[[*group_cols, 'mm_mean', 'pwc', 'dep_mean']]

    df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_full_output_2025-09-19.csv', index_col=0, encoding='utf-8')

    monthly_stats = monthly_precip_stats(
        df,
        start_col="start_dt",
        end_col="end_dt",
        mm_col="mm",
        conc_col="concentration",
        dep_col="deposition",
        flag_col="flag_orig",
        site_col="site"
    )

    # print(monthly_stats)
    monthly_stats.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\hgee_monthly_wet_deposition.csv', encoding='utf-8')

def seasonal_averaging():
    # read in wet dep data
    df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_full_output_2025-09-19.csv', encoding='utf-8')

    # Filtering step
    # read in the csv file for flag mapping
    flag_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\flag_mapping.csv')

    # Select Project_flag values where DES_flag is in ['M1', 'M2']
    flags_to_exclude = flag_df.loc[flag_df['DES_flag'].isin(['M1', 'M2']), 'Project_flag'] \
        .astype(str) \
        .str.strip() \
        .tolist()
    df.loc[df['flag_orig'].isin(flags_to_exclude), ['mm','concentration','deposition']] = pd.NA

    # remove negative values
    df[['mm','concentration','deposition']] = df[['mm','concentration','deposition']].mask(df[['mm','concentration','deposition']] < 0, pd.NA)

    # print (df['site'].unique())

   
    for column in ['datetime', 'start_dt', 'end_dt']:
        # Convert to string, split at space, keep only the first part
        df[column] = df[column].astype(str).str.split(' ').str[0]
        df[column] = pd.to_datetime(df[column], errors='coerce', utc=True)


    average_df = (
        df.loc[df['datetime'] > '2009-12-31', ['site', 'deposition']]
        .groupby('site', as_index=False)
        .mean(numeric_only=True)
    )    

    # add a month column
    df['month'] = df['datetime'].dt.month

    # add a year column
    df['year'] = df['datetime'].dt.year

    site_years = df.groupby('site')['year'].unique()
    print(site_years)

    average_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\results.csv', encoding='utf-8')

    # set the df season column
    df['season'] = ((df['month'] - 1) // 3) + 1 
    results = []

    for site, site_df in df.groupby('site', sort=False):  # loop through all sites
        # print (site)
        for year, year_df in site_df.groupby('year', sort=False):  # all years per site
            # print (year)
            for season, season_df in year_df.groupby('season', sort=False):  # all seasons per year
                # print (season)
                total_precip = season_df['mm'].sum()
                pwc = (season_df['mm'] * season_df['concentration']).sum() / total_precip if total_precip > 0 else np.nan

                results.append({
                    'site': site,
                    'year': year,
                    'season': season,
                    'mm_mean': season_df['mm'].mean(skipna=True),
                    'pwc': pwc,
                    'dep_mean': season_df['deposition'].mean(skipna=True),
                    'n_obs': len(season_df)
                })

    seasonal_df = pd.DataFrame(results)
    print (seasonal_df['site'].unique())

    # just grab LesperanceRanch
    lr_df = seasonal_df[seasonal_df['site'] == 'LesperanceRanch']
    lr_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\lr_df.csv', encoding='utf-8', index=False)

    # split up the dataframe by site and then do 4 side-by-side MK trends for each season for each site
    def mann_kendall_by_site_season(df, value_cols):
        """
        Runs pymannkendall.original_test for each site and calendar month for specified value columns.

        Parameters:
            df: pd.DataFrame containing at least ['site','month'] + value columns
            value_cols: list of columns to test (e.g. ['mm_mean','pwc','dep_mean'])

        Returns:
            pd.DataFrame with Mann-Kendall results for each site/month/value_col
        """

        results = []

        for site, site_df in df.groupby('site'):
            # print (site)
            for season_num, season_df in site_df.groupby('season'):
                season_df_sorted = season_df.sort_values(by='season')

                for col in value_cols:
                    series = season_df_sorted[col].dropna()
                    # print (series.head())

                    # determine an annual average for the first valid year of data
                    # Keep only valid numeric values
                    valid_series = series[(pd.notna(series)) & (series != 0)]

                    if valid_series.empty:
                        first_year_mean = np.nan
                    else:
                        first_year_mean = valid_series.iloc[:4].mean()
                        # print (f"First year mean for {site} {var} in {first_year}: {first_year_mean}")


                    if len(series) >= 3:  # mk requires at least 3 data points
                        test_result = mk.original_test(series)

                        results.append({
                            'site': site,
                            'season': season_num,
                            'variable': col,
                            'trend': test_result.trend,
                            'h': test_result.h,
                            'p': test_result.p,
                            'z': test_result.z,
                            'Tau': test_result.Tau,
                            's': test_result.s,
                            'var_s': test_result.var_s,
                            'slope': test_result.slope/first_year_mean*100,
                            'intercept': test_result.intercept
                        })

        return pd.DataFrame(results)


    # Example usage:
    value_columns = ['mm_mean', 'pwc', 'dep_mean']
    results_df = mann_kendall_by_site_season(seasonal_df, value_columns)       


    # seasonal_df to csv
    results_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_seasonal_M-K_results_2025-10-09.csv', index=False, encoding='utf-8')

def monthly_wet_dep_mk_results():
    df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_monthly_averages.csv', encoding='utf-8')

    def mann_kendall_by_site_month(df, value_cols):
        """
        Runs pymannkendall.original_test for each site and calendar month for specified value columns.

        Parameters:
            df: pd.DataFrame containing at least ['site','month'] + value columns
            value_cols: list of columns to test (e.g. ['mm_mean','pwc','dep_mean'])

        Returns:
            pd.DataFrame with Mann-Kendall results for each site/month/value_col
        """

        df['month_num'] = pd.to_datetime(df['month']).dt.month

        results = []

        for site, site_df in df.groupby('site'):
            for month_num, month_df in site_df.groupby('month_num'):
                month_df_sorted = month_df.sort_values(by='month')

                for col in value_cols:
                    series = month_df_sorted[col].dropna()

                    if len(series) >= 3:  # mk requires at least 3 data points
                        test_result = mk.original_test(series)

                        results.append({
                            'site': site,
                            'month': month_num,
                            'variable': col,
                            'trend': test_result.trend,
                            'h': test_result.h,
                            'p': test_result.p,
                            'z': test_result.z,
                            'Tau': test_result.Tau,
                            's': test_result.s,
                            'var_s': test_result.var_s,
                            'slope': test_result.slope,
                            'intercept': test_result.intercept
                        })

        return pd.DataFrame(results)


    # Example usage:
    value_columns = ['mm_mean', 'pwc', 'dep_mean']
    results_df = mann_kendall_by_site_month(df, value_columns)

    print(results_df)
    results_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_monthly_M-K_results_2025-10-09.csv', index=False, encoding='utf-8')


def annual_summary(sql_engine):

    def annual_slope_from_monthly(monthly_slopes, month_counts=None):
        """
        Compute annual slope as a weighted average of monthly slopes.
        Handles NaNs and non-finite values robustly.
        """
        # Convert list input to dict
        if isinstance(monthly_slopes, list):
            slopes = {i + 1: monthly_slopes[i] for i in range(len(monthly_slopes))}
        else:
            slopes = dict(monthly_slopes)

        # Default days per month (leap year)
        if month_counts is None:
            month_counts = {m: calendar.monthrange(2000, m)[1] for m in range(1, 13)}

        # Filter only valid numeric slopes
        valid_months = {
            m: float(v)
            for m, v in slopes.items()
            if pd.notna(v) and np.isfinite(v)
        }

        if not valid_months:
            return np.nan

        total_days = sum(month_counts[m] for m in valid_months.keys())
        if total_days == 0:
            print ("Total days is zero, cannot compute annual slope.")
            return np.nan

        weighted_sum = sum(valid_months[m] * month_counts[m] for m in valid_months)
        annual_slope = weighted_sum / total_days
        # print ("Annual slope calculated:", annual_slope)
        return annual_slope

    def annual_mannkendall_summary(mk_df):
        """
        Computes annual Mann-Kendall summary from monthly MK results.

        mk_df: pd.DataFrame with columns:
            ['site', 'variable', 'month', 'Tau', 'p', 'slope']

        Returns:
            pd.DataFrame with annual trends for each site and variable.
        """

        results = []

        for (site, variable), group in mk_df.groupby(['site', 'variable']):
            # print (site, variable)
            taus = group['Tau'].dropna().values
            ps = group['p'].dropna().values
            slopes = group['slope'].dropna().values

            if len(taus) == 0:
                continue

            # 1. Mean Tau (direction + strength)
            annual_tau = np.mean(taus)

            # 2. Mean slope
            annual_slope = annual_slope_from_monthly(
                {row['month']: row['slope'] for _, row in group.iterrows()}
            )


        # 3. Combine p-values using Fisher’s method
            if len(ps) > 0:
                chi_stat = -2 * np.sum(np.log(ps))
                combined_p = chi2.sf(chi_stat, 2 * len(ps))  # survival function (1-CDF)
            else:
                combined_p = np.nan

            # Determine direction of trend from Tau
            if annual_slope > 0 and combined_p < 0.05:
                annual_trend = "INCREASING"
            elif annual_slope < 0 and combined_p < 0.05:
                annual_trend = "DECREASING"
            else:
                annual_trend = "NO TREND"

            results.append({
                "SITE": site,
                "VARIABLE": variable,
                "ANNUAL SLOPE": annual_slope,
                "P VALUE": combined_p,
                "ANNUAL TREND": annual_trend
            })

        return pd.DataFrame(results)

    mk_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_monthly_M-K_results_2025-10-09.csv', encoding='utf-8')
    summary_df = annual_mannkendall_summary(mk_df)

    # grab the monthly average data as df
    monthly_wd_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_monthly_averages.csv', encoding='utf-8')
    monthly_wd_df['month'] = pd.to_datetime(monthly_wd_df['month'])
    results = []
    # Loop through sites
    for site, site_data in monthly_wd_df.groupby("site"):
        start_date = site_data["month"].min()
        end_date = site_data["month"].max()

        site_data = site_data[site_data['month'].dt.year >= 2010].copy()

        if site_data.empty:
            print(f"{site} | no data after 2010")
            continue
        
        for var in ["mm_mean", "pwc", "dep_mean"]:
            series = (
                site_data[["month", var]]
                .set_index("month")[var]        # <-- use month as index
                .dropna()
            )

            if not series.empty:
                min_value = series.min()
                min_month = series.idxmin()  # ← gets the index (month) of the min value
                print(f"{site} | {var} | min={min_value} in month {min_month}")
            else:
                print(f"{site} | {var} | no valid data")
                
            # Keep only valid numeric values
            valid_series = series[(pd.notna(series)) & (series != 0)]

            if valid_series.empty:
                first_year_mean = np.nan
            else:
                first_year = valid_series.index.year.min()
                first_year_mean = valid_series[valid_series.index.year == first_year].mean()
                # print (f"First year mean for {site} {var} in {first_year}: {first_year_mean}")

            if series.empty:
                continue

            results.append({
                "SITE": site,
                "START DATE": start_date,
                "END DATE": end_date,
                "VARIABLE": var,
                "MEAN": series.mean(),
                "MIN": series.min(),
                "MAX": series.max(),
                "25TH": series.quantile(0.25),
                "75TH": series.quantile(0.75),
                "FIRST YEAR": first_year_mean
            })
            print (site,var,series.min())

    # Final dataframe
    stats_df = pd.DataFrame(results) 

    summary_df = summary_df.merge(stats_df, on=["SITE", "VARIABLE"], how="left")

    summary_df['ANNUAL SLOPE'] = summary_df['ANNUAL SLOPE'] /summary_df['FIRST YEAR'] * 100
    summary_df = summary_df.drop(columns=['FIRST YEAR'])

    # grab the sites list from the sites table
    sql_data_query = """
                SELECT DISTINCT ON (site) 
                site AS "SITE",
                country AS "COUNTRY", 
                latdecd AS "LAT", 
                londecd AS "LON"
                FROM hgee_active
                ORDER BY site;
                """

    with sql_engine.connect() as conn:
        sites_df = pd.read_sql_query(sql_data_query, conn)
    
    sites_df['SITE'] = sites_df['SITE'].str.replace(" ", "", regex=False)
    summary_df['SITE'] = summary_df['SITE'].str.replace(" ", "", regex=False)
    summary_df = summary_df.merge(sites_df, left_on='SITE', right_on='SITE', how='left')
    summary_df.sort_values(by=['COUNTRY', 'SITE'], inplace=True)
    # print (summary_df.columns)
    # summary_df = summary_df[[
    #     "SITE", "COUNTRY", "LAT", "LON", "START DATE", "END DATE","VARIABLE",
    #     "MEAN", "MIN", "MAX", "25TH", "75TH",
    #     "ANNUAL SLOPE", "P VALUE", "ANNUAL TREND"
    # ]]
    summary_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_annual_M-K_results_2025-10-09.csv', index=False, encoding='utf-8')

def gantt_plotter(sql_engine):
    # # do a gantt chart of the data availability
    # # sql query to grab start and end dates from db
    # sql_data_query = """
    #         SELECT DISTINCT ON (site) 
    #         site as "SITE",
    #         country as "COUNTRY",
    #         TO_CHAR(MIN(datetime), 'YYYY-MM-DD') AS start_dt,
    #         TO_CHAR(MAX(datetime), 'YYYY-MM-DD') AS end_dt,
    #         ipcc_region
    #         FROM hgee_active
    #         WHERE start_dt IS NOT NULL AND end_dt IS NOT NULL
    #         AND matrix = 'precip'
    #         GROUP BY site, country, ipcc_region
    #         HAVING COUNT(deposition) > 0
    #         ORDER BY site;
    #         """

    # with sql_engine.connect() as conn:
    #     sites_df = pd.read_sql_query(sql_data_query, conn)

    # sites_df['SITE'] = sites_df['SITE'].str.replace(" ", "", regex=False)
    # sites_df['SITE'] = sites_df['SITE'].str.replace("'", "", regex=False)

    # # grab the sites and trends from the annual summary
    # annual_summary_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_annual_M-K_results_2025-10-09.csv', encoding='utf-8')
    # # filter to grab only the wet deposition trends
    # wet_dep_trends = annual_summary_df[annual_summary_df['VARIABLE'] == 'dep_mean']

    # # remove spaces and apostrophes from the SITE column
    # wet_dep_trends['SITE'] = wet_dep_trends['SITE'].str.replace(" ", "", regex=False)
    # wet_dep_trends['SITE'] = wet_dep_trends['SITE'].str.replace("'", "", regex=False)

    # # print unique sites in wet_dep_trends not in sites_df
    # missing_sites = set(wet_dep_trends['SITE']) - set(sites_df['SITE'])
    # if missing_sites:
    #     print("Missing sites in sites_df:", missing_sites)  
    
    # # merge the two dataframes to get the trends with the start and end dates
    # merged_df = wet_dep_trends.merge(sites_df, on=['SITE', 'COUNTRY'], how='right')

    # # print length of merged_df
    # print("Length of merged_df:", len(merged_df))

    # # include the missing sites from the wet_dep_trends dataframe in the merged dataframe
    # merged_df = pd.concat([merged_df, wet_dep_trends[wet_dep_trends['SITE'].isin(missing_sites)]], ignore_index=True)

    # # print length of merged_df
    # print("Length of merged_df:", len(merged_df))



    # # set the start_dt and end_dt to datetime
    # merged_df['start_dt'] = pd.to_datetime(merged_df['start_dt'])
    # merged_df['end_dt'] = pd.to_datetime(merged_df['end_dt']) 

    # # replace 'ipcc_region' where '*Europe*' in 'ipcc_region' with 'Europe'
    # merged_df['ipcc_region'] = merged_df['ipcc_region'].replace(r'.*Europe', 'Europe', regex=True)

    # # # replace 'ipcc_region' where '*Asia*' in 'ipcc_region' with 'Asia'
    # # merged_df['ipcc_region'] = merged_df['ipcc_region'].replace(r'.* Asia', 'Asia', regex=True) 





    # # output the merged dataframe to a csv
    # merged_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_gantt_data_merged.csv', index=False, encoding='utf-8')

    # read in the merged dataframe from csv
    merged_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_gantt_data_merged.csv', encoding='utf-8')
    merged_df['start_dt'] = pd.to_datetime(merged_df['start_dt'], errors="coerce")
    merged_df['end_dt'] = pd.to_datetime(merged_df['end_dt'], errors="coerce")

    # replace Nan with 'NOT MEASURED' in the ANNUAL TREND column
    merged_df['ANNUAL TREND'] = merged_df['ANNUAL TREND'].fillna('NOT MEASURED')

    # create a dictionary to assign a colour to each site based on whether the trend is increasing, decreasing or no trend
    trend_colors = {
        'INCREASING': 'red',
        'DECREASING': 'blue',
        'NO TREND': 'gray',
        'NOT MEASURED': 'black'
    }

    # create a dictionary to assign a colour to each site based on whether the trend is increasing, decreasing or no trend    # add the line colour column to the dataframe
    merged_df['line_color'] = merged_df['ANNUAL TREND'].map(trend_colors)

    # grab the country-codes
    country_code_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\iso_2digit_alpha_country_codes.csv', encoding='utf-8')

    # merge the two dfs together on 'country'
    merged_df = merged_df.merge(country_code_df, left_on  = 'COUNTRY', right_on = 'country', how = 'left')
                                   
    # find and print sites with missing country codes
    missing_countries = merged_df[merged_df['country_code'].isna()]
    if not missing_countries.empty:
        print("⚠️ Sites with missing country codes:")
        print(missing_countries[['site', 'COUNTRY']])
    else:
        print("✅ All sites have country codes")

    # merge the site and country columns
    merged_df['SITE'] = merged_df['SITE'] + ', ' + merged_df['country_code']

    

    # dictionary of figure sizes based on number of sites
    region_figsizes = {
        "C.North-America": (10, 8),
        "E.North-America": (12, 16),
        "W.North-America": (10, 8),
        "N.W.North-America": (10, 4),
        "Europe": (10, 6),
        "E.Asia": (10, 2),
        "Asia": (10, 6),
        "Southern-Hemisphere": (10, 2),
        "Central-America": (10, 6),
        "Mediterranean": (10, 6),
        "Polar-Regions": (10, 6),
        "Africa": (10, 6),
        "default": (10, 6)
    }
    for region in merged_df['ipcc_region'].unique():
        region_df = merged_df[merged_df['ipcc_region'] == region]

        # sort the dataframe by end date then start date descending
        region_df = region_df.sort_values(by=['end_dt', 'start_dt'], ascending=[True, True])
        # reset the index
        region_df = region_df.reset_index(drop=True)
        fig, ax = plt.subplots(figsize=region_figsizes.get(region, region_figsizes["default"]))
        # set line colour based on trend
    # --- Plot each site's data availability as a horizontal line ---
        for _, row in region_df.iterrows():
            ax.hlines(
                y=row['SITE'],
                xmin=row['start_dt'],
                xmax=row['end_dt'],
                color=row['line_color'],
                linewidth=4  # adjust thickness
            )
        ax.xaxis_date()  # ensures proper datetime axis
        ax.set_xlabel('Date')
        ax.set_ylabel('Site')
        ax.set_title(f'Wet Deposition Data Availability Gantt Chart - {region}')
        handles = [Patch(color=c, label=trend) for trend, c in trend_colors.items()]
        ax.legend(handles=handles, title="Wet Dep Trend", bbox_to_anchor=(1.05, 1), loc="upper left")
        plt.tight_layout()
        out_dir = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots'
        outfile = os.path.join(out_dir, f"wd_gantt_chart_{region}.png")
        plt.savefig(outfile)
        plt.close()

def mdn_assimilator():
    # Extract site names from the main CSV
    output_path = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_mdn_output_2025-10-20.csv'

    # initialize a wet dep dataframe
    mdn_wd_df = pd.DataFrame(columns=['datetime', 'start_dt', 'end_dt', 'project', 'ipcc_region', 'country', 'site', 'latdecd', 'londecd', 'precipitation', 'precipitation_units', 'concentration', 'concentration_units', 'deposition', 'deposition_units', 'flag_orig', 'flag_des'])
    
    # read in a site df
    site_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\site_look_up.csv', index_col=0)
   
    # read in a flag dataframe
    flag_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\flag_mapping.csv', index_col=0)

    canada_files = glob.glob(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Data\Canada\precip_data\minamata_format\*.csv')
    us_files = glob.glob(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Data\US\precip_data\minamata_format\*.csv')

    # add the two lists
    files = canada_files + us_files
    
    bad_files = []
    for file in files:
        with open(file, 'r') as f:
            lines = f.readlines()
        # ------------------------------------------------------------------
        # Extract header/site information BEFORE the "Data Table Start" line.
        # We assume each header line is formatted with a keyword followed by a tab and then a value.
        # ------------------------------------------------------------------
        header_info = {}
        data_start_idx = None
        for i, line in enumerate(lines):
            if line.startswith("*SITE IDENTIFICATION"):
                parts = line.strip().split(',')
                print (parts)
                if len(parts) > 1:
                    header_info['site'] = parts[1]
            elif line.startswith("*SITE COUNTRY"):
                parts = line.strip().split(',')
                if len(parts) > 1:
                    # Map "USA" to "United States" if needed.
                    header_info['country'] = "United States" if parts[1] == "USA" else parts[1]
            elif line.startswith("*SITE LATITUDE,"):
                parts = line.strip().split(',')
                if len(parts) > 1:
                    header_info['latdecd'] = parts[1]
            elif line.startswith("*SITE LONGITUDE,"):
                parts = line.strip().split(',')
                if len(parts) > 1:
                    header_info['londecd'] = parts[1]
            elif "Data Table Start" in line:
                data_start_idx = i + 1  # Data columns header should be on the next line.
                break

        # Check we found the start of the data table.
        if data_start_idx is None:
            print(f"Data Table Start not found in {file}. Skipping file.")
            bad_files.append(os.path.basename(file))
            continue

        # ------------------------------------------------------------------
        # Read in the data portion of the file starting after the "Data Table Start" line.
        # Assume the fields in the file are tab-delimited.
        # ------------------------------------------------------------------
        data_str = "".join(lines[data_start_idx:])
        mdn_df = pd.read_csv(StringIO(data_str), sep=',')

        # ------------------------------------------------------------------
        # Map MDN file columns to mdn_wd_df columns.
        # (Assuming the MDN file has these columns in the data table:)
        # dateOn -> start_dt, dateOff -> end_dt, and we copy dateOff as datetime.
        # qr -> flag_orig, subppt -> precipitation, HgConc -> concentration, HgDep -> deposition.
        # ------------------------------------------------------------------
        mdn_df['start_dt'] = mdn_df['dateOn'].astype(str).str.split().str[0]
        mdn_df['end_dt'] = mdn_df['dateOff'].astype(str).str.split().str[0]
        mdn_df['datetime'] = mdn_df['dateOff'].astype(str).str.split().str[0]
        mdn_df.rename(columns={
            'qr': 'flag_orig',
            'subppt': 'precipitation',
            'HgConc': 'concentration',
            'HgDep': 'deposition'
        }, inplace=True)

        # ------------------------------------------------------------------
        # Set constant units values.
        # ------------------------------------------------------------------
        mdn_df['precipitation_units'] = 'mm/wk'
        mdn_df['concentration_units'] = 'ng/L'
        mdn_df['deposition_units'] = 'ng/m2wk'

        # ------------------------------------------------------------------
        # Add header-derived information to every row (site, country, latitude, longitude).
        # ------------------------------------------------------------------
        for key in ['site', 'country', 'latdecd', 'londecd']:
            mdn_df[key] = header_info.get(key, None)

        # Optionally, set the project value (hard-coded here, modify as needed)
        mdn_df['project'] = 'MDN'

        # ------------------------------------------------------------------
        # Look up additional info from site_df.
        # Retrieve continent and ipcc_region based on the site name.
        # ------------------------------------------------------------------
        current_site = header_info.get('site')
        if current_site is not None and current_site in site_df.index.unique():
            mdn_df['continent'] = site_df.loc[site_df.index == current_site, 'continent'].iloc[0]
            mdn_df['ipcc_region'] = site_df.loc[site_df.index == current_site, 'ipcc_region'].iloc[0]
        else:
            mdn_df['continent'] = None
            mdn_df['ipcc_region'] = None

        # ------------------------------------------------------------------
        # Look up flag_des from flag_df using the value in flag_orig.
        # Assuming flag_df's index corresponds to flag_orig values and that it has a column "flag_des".
        # ------------------------------------------------------------------
        def get_flag_des(flag):
            try:
                return flag_df.loc[flag_df.index == flag, 'flag_des'].iloc[0]
            except:
                return None

        mdn_df['flag_des'] = mdn_df['flag_orig'].apply(get_flag_des)

        # ------------------------------------------------------------------
        # Reorder the columns to match the mdn_wd_df structure.
        # Note: If a field is not present or extra fields exist, adjust accordingly.
        # ------------------------------------------------------------------
        desired_cols = ['datetime', 'start_dt', 'end_dt', 'project', 'ipcc_region', 'country', 'site', 
                        'latdecd', 'londecd', 'precipitation', 'precipitation_units', 
                        'concentration', 'concentration_units', 'deposition', 'deposition_units', 
                        'flag_orig', 'flag_des', 'continent']
        mdn_df = mdn_df[desired_cols]

        # ------------------------------------------------------------------
        # Append this MDN file’s data to the overall mdn_wd_df.
        # ------------------------------------------------------------------
        mdn_wd_df = pd.concat([mdn_wd_df, mdn_df], ignore_index=True)
    
    
    new_order = [
            'datetime', 'site', 'start_dt', 'end_dt', 'project', 'country',
            'ipcc_region', 'continent', 'latdecd', 'londecd', 'precipitation',
            'precipitation_units', 'concentration', 'concentration_units',
            'deposition', 'deposition_units', 'flag_orig', 'flag_des'
            ]
    mdn_wd_df = mdn_wd_df[new_order]

    cols_to_clean = ["precipitation", "concentration", "deposition"]

    # 1. Replace -9 and -9.0 with -999 for all target columns at once
    mdn_wd_df[cols_to_clean] = mdn_wd_df[cols_to_clean].replace([-9, -9.0], -999)

    # 2. Identify rows where ANY target col is -999
    mask = (mdn_wd_df[cols_to_clean] == -999).any(axis=1)

    # 3. Flag those rows
    mdn_wd_df.loc[mask, "flag_orig"] = "C"
    mdn_wd_df.loc[mask, "flag_des"] = "M2"

    # 4. Mask for bad flag ('flag_des' == 'M1' or 'M2')
    bad_flag_mask = mdn_wd_df['flag_des'].isin(['M1', 'M2'])

    # 5. Replace values with -999 for all target columns where bad_flag_mask True
    mdn_wd_df.loc[bad_flag_mask, cols_to_clean] = -999

    # 6. Round values for non-flagged rows (all columns at once)
    good_flag_mask = ~bad_flag_mask
    mdn_wd_df.loc[good_flag_mask, cols_to_clean] = mdn_wd_df.loc[good_flag_mask, cols_to_clean].round(3)


    # remove apostrophes from site names
    mdn_wd_df['site'] = mdn_wd_df['site'].str.replace(r"[.']", '', regex=True)

    mdn_wd_df.to_csv(output_path, index = False)
    with open(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\bad_mdn_files.txt', 'w') as f:
        for file in bad_files:
            f.write(file + '\n')

def ebas_wd_assimilator():
    ebas_wd_path = r'C:\Users\firanskib\Documents\hg_bernard_2025_1125\*'
    # ebas_wd_path = r'C:\Users\firanskib\OneDrive - EC-EC\mercury\EBAS\test\*'

    # read in a site df
    site_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\site_look_up.csv', index_col=0)
   
    # read in a flag dataframe
    flag_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\flag_mapping.csv', index_col=0)

    ebas_files = glob.glob(ebas_wd_path)

    # -------------------------------------------------------------------------
    # --- Utility functions ---
    # -------------------------------------------------------------------------
    def normalize_flag(flag_value):
        """Convert erroneous decimal flags into 3-digit strings."""
        if pd.isna(flag_value):
            return None
        flag_int = int(float(flag_value) * 1000)
        return str(flag_int).zfill(3)[:3]


    def map_flag_des(flag_orig, flag_df):
        """Map numeric flag to descriptive flag."""
        try:
            return flag_df.loc[flag_df.index == flag_orig, 'flag_des'].iloc[0]
        except IndexError:
            return None


    def determine_flag_orig(row, flag_df):
        """Determine preferred flag_orig using M1/M2/V0 priority, including single 'flag' column."""
        flags = []

        # Scenario 1: separate flag_mm / flag_Hg columns
        if 'flag_mm' in row and pd.notna(row['flag_mm']):
            flags.append(normalize_flag(row['flag_mm']))
        if 'flag_Hg' in row and pd.notna(row['flag_Hg']):
            flags.append(normalize_flag(row['flag_Hg']))

        # Scenario 2: single 'flag' column exists
        if not flags and 'flag' in row and pd.notna(row['flag']):
            flags.append(normalize_flag(row['flag']))

        if not flags:
            return None

        # Map to descriptive flags
        flag_map = {f: map_flag_des(f, flag_df) for f in flags}

        # Scenario 1 priority logic: M1 > M2 > fallback
        for f, des in flag_map.items():
            if des == 'M1':
                return f
        for f, des in flag_map.items():
            if des == 'M2':
                return f

        # Fallback: just return the first flag
        return flags[0]

    # -------------------------------------------------------------------------
    # --- Core NAS parser ---
    # -------------------------------------------------------------------------
    def parse_ebas_nas_standardized(nas_file, site_df, flag_df):
        nas_file = Path(nas_file)
        print ('Processing EBAS NAS file:', nas_file.name)
        with open(nas_file, "r", encoding="utf-8") as f:
            lines = [line.strip() for line in f if line.strip()]

        # --- Reference date ---
        ref_parts = lines[6].split()
        ref_date = dt.datetime(int(ref_parts[0]), int(ref_parts[1]), int(ref_parts[2]))

        # --- Extract site info ---
        site, lat, lon = None, None, None
        for line in lines[:60]:
            if "Station name" in line:
                site = line.split(":")[-1].strip()
            elif "Station latitude" in line:
                lat = float(line.split(":")[-1].strip())
            elif "Station longitude" in line:
                lon = float(line.split(":")[-1].strip())

        # --- Data section ---
        start_idx = next(i for i, line in enumerate(lines) if line.startswith("starttime"))
        raw_cols = re.split(r"\s+", lines[start_idx].strip())

        # Enumerate duplicate column names: mm_0, mm_1, mm_2, ...
        cols = (
            pd.Series(raw_cols)
            .groupby(raw_cols)
            .cumcount()
            .astype(str)
            .radd('_')
            .radd(pd.Series(raw_cols))
        )

        # print ('Columns detected:', cols.tolist())

        # --- Read data rows ---
        data = []
        for line in lines[start_idx + 1:]:
            if not re.match(r"^[-\d]", line):
                break
            data.append(re.split(r"\s+", line.strip()))

        df = pd.DataFrame(data, columns=cols).apply(pd.to_numeric, errors="coerce")

        # --- Keep only the highest index columns for each variable ---
        idx = (
        pd.Series(df.columns)
        .str.rsplit("_", n=1, expand=True)
        .assign(n=lambda x: x[1].astype(int))
        .groupby(0)["n"]
        .idxmax()
    )

        df = df.iloc[:, idx.sort_values()]

        # drop column suffixes
        df.columns = df.columns.str.replace(r"_\d+$", "", regex=True)

        # --- Date handling ---
        df['start_dt'] = df['starttime'].apply(lambda x: ref_date + dt.timedelta(days=float(x)))
        df['end_dt']   = df['endtime'].apply(lambda x: ref_date + dt.timedelta(days=float(x)))
        df['datetime'] = df['end_dt']

        # Convert to string YYYY-MM-DD
        df[['start_dt', 'end_dt', 'datetime']] = df[['start_dt', 'end_dt', 'datetime']].apply(
            lambda x: x.dt.strftime('%Y-%m-%d')
        )

        # --- Assign standardized columns ---
        df['site'] = site
        site_row = site_df.loc[site_df.index == site].squeeze() if site in site_df.index.values else {}
        df['project'] = 'EBAS'
        df['country'] = site_row.get('country', None)
        df['ipcc_region'] = site_row.get('ipcc_region', None)
        df['continent'] = site_row.get('continent', None)
        df['latdecd'] = lat
        df['londecd'] = lon

        # --- Map precipitation / mercury ---
        df['precipitation'] = df['mm'] if 'mm' in df.columns else None
        df['concentration'] = df['Hg'] if 'Hg' in df.columns else None
        df['precipitation_units'] = 'mm/wk'
        df['concentration_units'] = 'ng/L'
        df['deposition'] = df['precipitation'] * df['concentration']
        df['deposition_units'] = 'ng/m2wk'

        # --- Flag handling ---
        df['flag_orig'] = df.apply(determine_flag_orig, axis=1, flag_df=flag_df)
        df['flag_des'] = df['flag_orig'].apply(lambda f: map_flag_des(f, flag_df))

        # --- Final standardized columns ---
        cols = [
            'datetime', 'site', 'start_dt', 'end_dt', 'project', 'country', 'ipcc_region', 'continent',
            'latdecd', 'londecd', 'precipitation', 'precipitation_units', 'concentration',
            'concentration_units', 'deposition', 'deposition_units', 'flag_orig', 'flag_des'
        ]
        return df[cols]


    # -------------------------------------------------------------------------
    # --- Batch processing ---
    # -------------------------------------------------------------------------
    def process_all_ebas_files(ebas_path, site_df, flag_df):
        all_files = glob.glob(ebas_path)
        processed_dfs = []

        for nas_file in all_files:
            # try:
            #     df = parse_ebas_nas_standardized(nas_file, site_df, flag_df)
            #     processed_dfs.append(df)
            # except Exception as e:
            #     print(f"⚠️ Error processing {nas_file}: {e}")

            df = parse_ebas_nas_standardized(nas_file, site_df, flag_df)
            processed_dfs.append(df)

        df_all = pd.concat(processed_dfs, ignore_index=True)

        # --- Merge duplicates on (site, datetime) ---
        merged_rows = []
        grouped = df_all.groupby(['site', 'datetime'], dropna=False)

        for _, g in grouped:
            row = g.iloc[0].copy()

            # If both precip & Hg exist in different rows, combine
            if g['precipitation'].notna().any() and g['concentration'].notna().any():
                row['precipitation'] = g['precipitation'].dropna().iloc[0]
                row['concentration'] = g['concentration'].dropna().iloc[0]
                row['deposition'] = row['precipitation'] * row['concentration']

            # Merge flags using M1/M2/V0 priority logic
            merged_flags = g[['flag_orig', 'flag_des']].dropna()
            if not merged_flags.empty:
                # Use same logic as row-level flag merge
                flag_candidates = merged_flags['flag_orig'].unique().tolist()
                flag_map = {f: map_flag_des(f, flag_df) for f in flag_candidates}
                if 'M1' in flag_map.values():
                    chosen_flag = [f for f, des in flag_map.items() if des == 'M1'][0]
                elif 'M2' in flag_map.values():
                    chosen_flag = [f for f, des in flag_map.items() if des == 'M2'][0]
                else:
                    chosen_flag = flag_candidates[0]
                row['flag_orig'] = chosen_flag
                row['flag_des'] = map_flag_des(chosen_flag, flag_df)

            merged_rows.append(row)

        return pd.DataFrame(merged_rows)

    ebas_wd_df = process_all_ebas_files(ebas_wd_path, site_df, flag_df)

    # clean up ebas_wd_df['site'] to remove spaces and apostrophes
    ebas_wd_df['site'] = ebas_wd_df['site'].str.replace(r"[.']", '', regex=True).str.replace(" ", "", regex=False)

    # clean up the data to remove bad data

    cols_to_clean = ["precipitation", "concentration", "deposition"]

    # 1. Identify rows with NaN in any target column (before filling!)
    nan_mask = ebas_wd_df[cols_to_clean].isna()
    any_nan = nan_mask.any(axis=1)         # True for any row where at least one target col is NaN

    # 2. Update flags for those rows
    ebas_wd_df.loc[any_nan, "flag_orig"] = "999"
    ebas_wd_df.loc[any_nan, "flag_des"] = "M1"

    # 3. Fill NaNs with -999 for all target columns at once
    ebas_wd_df[cols_to_clean] = ebas_wd_df[cols_to_clean].fillna(-999)

    # 4. Mask for bad flags (missing or invalid data: M1, M2)
    bad_flag_mask = ebas_wd_df['flag_des'].isin(['M1', 'M2'])

    # 5. Replace data with -999 wherever flag_des indicates missing/invalid
    ebas_wd_df.loc[bad_flag_mask, cols_to_clean] = -999

    # 6. Round the column to 3 decimal places in non-flagged rows
    good_flag_mask = ~bad_flag_mask
    ebas_wd_df.loc[good_flag_mask, cols_to_clean] = (
        ebas_wd_df.loc[good_flag_mask, cols_to_clean].round(3)
)           


    site_map = {
        "YarnerWood": "Yarner Wood",
        "Kårvatn": "Kårvatn",
        "Kotinen": "Kotinen",
        "VirolahtiIII": "Virolahti III",
        "VirolahtiII": "Virolahti II",
        "Gårdsjön": "Gårdsjön",
        "Vavihill": "Vavihill",
        "Rörvik": "Rörvik",
        "Kise": "Kise",
        "Hurdal": "Hurdal",
        "PeyrusseVieille": "Peyrusse Vieille",
        "TurloughHill": "Turlough Hill",
        "ValentiaObservatory": "Valentia Observatory",
        "Chilton": "Chilton",
        "HeighamHolmes": "Heigham Holmes",
        "Lahemaa": "Lahemaa",
        "StaxtonWold": "Staxton Wold",
        "Ulborg": "Ulborg",
        "Aspvreten": "Aspvreten",
        "Knokke": "Knokke",
        "Kosetice(NAOK)": "Kosetice (NAOK)",
        "Hyytiälä": "Hyytiälä",
        "ChilboltonObservatory": "Chilbolton Observatory",
        "DiablaGora": "Diabla Gora",
        "Banchory": "Banchory",
        "Lista": "Lista",
        "VirolahtiHarju": "Virolahti Harju",
        "Harwell": "Harwell",
        "Zoseni": "Zoseni",
        "EastRuston": "East Ruston",
        "Birkenes": "Birkenes",
        "Szymbark": "Szymbark",
        "AuchencorthMoss": "Auchencorth Moss",
        "MossObservatory": "Moss Observatory",
    }

    ebas_wd_df["site"] = ebas_wd_df["site"].replace(site_map)

    # output the standardized ebas wet dep data to csv    
    out_file = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_ebas_output_2025-12-30.csv'
    ebas_wd_df.to_csv(out_file, index=False)
    print(f"Saved standardized EBAS data to: {out_file}")


def wet_dep_comparison():
    # read in the two wet dep dataframes

    base_keys = ["datetime", "site"]

    table_wd_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wet_dep_export.csv')
    ebas_wd_df = pd.read_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_ebas_update_output_2025-12-30.csv')

    # list the sites that are in both dataframes
    sites_in_ebas = set(ebas_wd_df['site'].unique())
    sites_in_table = set(table_wd_df['site'].unique())

    print (f"sites in EBAS data: {sites_in_ebas}")
    print (f"sites in Table data: {sites_in_table}")

    sites_in_both = sites_in_ebas & sites_in_table
    print (f"sites in both dataframes: {sites_in_both}")

    # compare the entries in ebas to those in the table for the sites in both
    ebas_subset = ebas_wd_df[ebas_wd_df['site'].isin(sites_in_both)]

    candidates = (ebas_subset.merge(
            table_wd_df[base_keys + ["project"]],
            on=base_keys,
            how="left",
            suffixes=("_ebas", "_table"),
            indicator=True
        )
    )

    new_rows = candidates[
        (candidates["_merge"] == "left_only") |
        (
            (candidates["_merge"] == "both") &
            (~candidates.apply(
                lambda r: (
                    False
                    if pd.isna(r["project_table"])
                    else r["project_ebas"] in r["project_table"]
                ),
                axis=1
            ))
        )
    ].drop(columns="_merge")    
    # save the new sites to a csv
    new_rows.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_new_rows.csv', index=False)


    # table_wd_df["datetime"] = pd.to_datetime(table_wd_df["datetime"])
    # ebas_wd_df["datetime"] = pd.to_datetime(ebas_wd_df["datetime"])


    # table_wd_df["project"] = table_wd_df["project"].astype(str).str.strip()
    # ebas_wd_df["project"] = ebas_wd_df["project"].astype(str).str.strip()

    # new_rows = (
    #     ebas_wd_df
    #     .merge(table_wd_df, on=key_cols, how="left", indicator=True)
    #     .query("_merge == 'left_only'")
    #     .drop(columns="_merge")
    # )

    # print(f"New rows to insert: {len(new_rows)}")
    # print(new_rows.head())
    


def wd_check():
    # do a check for issues in the wet dep data
    # read in the wet dep data
    wd_data_path = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_additional_output.csv'
    wd_df = pd.read_csv(wd_data_path, encoding='utf-8')

    # print the length of the dataframe
    print(f"Length of wet dep dataframe: {len(wd_df)}")


    # print(f"Number of missing site names: {len(missing_sites)}")
    # check for repeat combinations of site datetime
    repeat_combinations = wd_df[wd_df.duplicated(subset=['site', 'datetime'], keep=False)]  
    print(f"Number of repeat site-datetime combinations: {len(repeat_combinations)}")
    # print which sites and datetimes are in the repeat combinations subset
    if not repeat_combinations.empty:
        print("Sites with repeat combinations:")
        print(repeat_combinations[['site', 'datetime']])


    # Only consider rows with valid data
    mask_valid = (wd_df['precipitation'] != -999) & (wd_df['concentration'] != -999)&(wd_df['project'] == 'MDN')

    # Calculate expected deposition
    expected_dep = wd_df.loc[mask_valid, 'precipitation'] * wd_df.loc[mask_valid, 'concentration']

    # replace wd dataframe deposition column with expected deposition for valid rows
    wd_df.loc[mask_valid, 'deposition'] = expected_dep


    # Flag rows where deposition differs by more than 10%
    tolerance = 0.10  # 10%
    nonsensical_mask = mask_valid & (
        np.abs(wd_df['deposition'] - expected_dep) / expected_dep > tolerance
    )

    # Extract problematic rows
    nonsensical_dep = wd_df[nonsensical_mask]  

    # print description of the nonsensical deposition values
    print("Description of nonsensical deposition values:")  
    print(nonsensical_dep.describe())

    # output the nonsensical deposition values to a csv
    nonsensical_dep.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_nonsensical_deposition_2025-10-28.csv', index=False, encoding='utf-8')

    # replace wd_df['deposition'] where wd_df['deposition']==0 and != -999 with -999
    wd_df.loc[(wd_df['deposition'] == 0) & (wd_df['precipitation'] ==0), ['deposition','flag_des']] = [-999, 'M2']    

    # check for bad values not flagged as M1 or M2
    bad_values = wd_df[~wd_df['flag_des'].isin(['M1', 'M2'])]
    bad_values = bad_values[
        (((bad_values['concentration'] <= 0) & (bad_values['concentration'] != -999)) |
        ((bad_values['deposition'] <= 0) & (bad_values['deposition'] != -999)))]
    
    print(f"Number of bad values not flagged as M1 or M2: {len(bad_values)}")

    # round concentration and deposition to 3 decimal places
    wd_df['concentration'] = wd_df['concentration'].round(3)
    wd_df['deposition'] = wd_df['deposition'].round(3)
    wd_df['precipitation'] = wd_df['precipitation'].round(3)


    # print the bad values to a csv
    wd_df.to_csv(r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\wd_output_2025-11-05.csv', index=False, encoding='utf-8')

# a dataframe uploader
def upload_dataframe_to_sql(sql_engine):
    # set the upload filepath
    filepath = r'\\econm3hwvfsp008.ncr.int.ec.gc.ca\arqp_data\Projects\OnGoing\Mercury\HGEE-Minamata\Results and Plots\test.csv'
    # upload the csv to pandas dataframe
    df = pd.read_csv(filepath, encoding='utf-8', index_col=False)
    # print the columns of the dataframe
    print(f"Columns in dataframe: {df.columns.tolist()}")

    # print the dataframe head
    print (df['datetime'])

    print(df.index)
    print(df.index.name)

    # get the raw psycopg2 connection
    conn = sql_engine.raw_connection()
    try:
        cur = conn.cursor()
        with open(filepath, "r", encoding="utf-8") as f:
            sql = """
                COPY wet_dep
                FROM STDIN
                WITH (FORMAT csv, HEADER true, DELIMITER ',');
            """
            cur.copy_expert(sql=sql, file=f)
        conn.commit()
        print("✅ Uploaded dataframe to SQL table: wet_dep")
    except Exception as e:
        conn.rollback()
        print(f"❌ Error during upload: {e}")
    finally:
        cur.close()
        conn.close()
# run monthly averaging
# monthly_averaging()

# run the wet_dep mk test
# monthly_wet_dep_mk_results()

# run seasonal_average
# seasonal_averaging()

# run the annual summary
# annual_summary(sql_engine)

# run the gantt plotter
# gantt_plotter(sql_engine)

# run an mdn assimilator
# mdn_assimilator()

# run an ebas wet dep assimilator
# ebas_wd_assimilator()

# run a wet dep comparison
wet_dep_comparison()

# do a check for issues
# wd_check()

# run the uploader function
# upload_dataframe_to_sql(sql_engine)


